### ISSUE TITLE
Epic 1 Goals

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ai_genomics#32]
- [x] Collect data relevant across research data, patent data, business data and funding data
- [x] Conduct EDA and DQA across the relevant datasets
- [ ] Improve collective domain knowledge and subject expertise of AI and genomics
- [ ] Solidify agile ways of working
- [x] Define whether this data collection work should sit within this project repo or beyond it
