### ISSUE TITLE
Dataset joining based on entity matching

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ai_genomics#54]
As part of the project deliverable, we are also interested in joining datasets to analyse. We would then need to:

- [ ] Identify common entities across all the datasets we've collected so far i.e. a company name
- [ ] We will need to identify a strategy to join datasets based on an entities i.e. use jacchammer? Are there other entity matching algorithms we want to explore? What preprocessing will we need to do to join? 
- [ ] Justify why we need joins - is this to help with analysis? Which analysis? Is this to expand data collection?
- [ ] Develop an evaluation strategy for joining i.e. develop a ground truth dataset of the same entity across different datasets - report on how many entities do we in/correctly join etc.? How do these metrics change subject to different entity matching algorithms and preprocessing methods?     

[from @Juan-Mateos] Potential joins:
- orgs from patent data w/ crunchbase
- expanding list of crunchbase companies based on patent join

Other ideas:
- join named patent inventors w/ OpenAlex's publisher or display_name
