### ISSUE TITLE
Generate samples for expert validation

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/ai_genomics#90]
- [x] Generate samples of abstracts
  - [x] >50 abstracts from publications and patents
  - [x] CPC patent codes used in definition augmentated with descriptions and taxonomy context
  - [x] IPC patent codes used in definition augmented with descriptions and taxonomy context
  - [x] OpenAlex concepts used in definition augmented with descriptions and taxonomy context
- [x] Create a method for splitting the samples according to the number of contributors
- [x] Analyse highest frequency codes to further filter if there are fewer contributors
